import os
import glob

# Rutas a buscar (todas las carpetas bajo app que tengan Report.jsx en la ruta específica)
files = glob.glob("/Users/glynne/Desktop/SERVEX_AI/app/**/Report.jsx", recursive=True)

translations = {
    "Panel de Control / Insights / Auditoría de Cambios": "Control Panel / Insights / Change Audit",
    "Últimos Reportes Generados": "Latest Generated Reports",
    "Filtrar por marca...": "Filter by brand...",
    "No se encontraron reportes previos": "No previous reports found",
    "Detalles de Auditoría en Tiempo Real": "Real-time Audit Details",
    "Extracción y análisis sintético de mutaciones JSON generadas por el flujo.": "Extraction and synthetic analysis of JSON mutations generated by the flow.",
    "Selecciona un reporte de la lista para ver los detalles.": "Select a report from the list to view details.",
    "Valor Original": "Original Value",
    "Nuevo Valor": "New Value",
    "% Dif": "% Diff",
    "No se registraron variaciones de precio.": "No price variations were recorded.",
    "Modelos Nuevos Detectados": "New Models Detected",
    "Nuevo SKU": "New SKU",
    "No se detectaron nuevos modelos en el origen.": "No new models were detected at the source.",
    "Modelos Removidos del Catálogo": "Models Removed from Catalog",
    "Descontinuado": "Discontinued",
    "No se detectaron modelos removidos.": "No removed models were detected."
}

updated_count = 0

for file_path in files:
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original_content = content
    for es, en in translations.items():
        content = content.replace(es, en)
        
    if content != original_content:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        updated_count += 1
        print(f"Translated: {file_path}")

print(f"Done. Translated {updated_count} files.")
