'use client';

import { useState } from 'react';
import Image from 'next/image';
import { motion, AnimatePresence } from 'framer-motion';

// ====================================================================
// MODAL
// ====================================================================

function SimpleModal({ isOpen, onClose, title, description }) {
  if (!isOpen) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          className="
            fixed inset-0 z-50
            flex items-center justify-center
            p-4 sm:p-6
            backdrop-filter backdrop-blur-md
          "
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          onClick={onClose}
        >
          <motion.div
            className="
              relative
              w-full max-w-lg
              bg-white
              rounded-xl shadow-2xl
              p-6 sm:p-8
            "
            initial={{ y: -50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 50, opacity: 0 }}
            transition={{ type: 'spring', stiffness: 100, damping: 20 }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* TITLE */}
            <h2
              className="
                text-xl sm:text-2xl
                font-semibold
                tracking-tight
                text-black
                mb-3
              "
            >
              {title}
            </h2>

            {/* DESCRIPTION */}
            <p
              className="
                text-xs sm:text-sm md:text-base
                text-black/60
                leading-relaxed
              "
            >
              {description}
            </p>

            <button
              onClick={onClose}
              className="
                mt-6 inline-flex justify-center
                rounded-full
                bg-black px-4 py-2
                text-sm font-medium text-white
                shadow-sm hover:bg-gray-800
                transition
              "
            >
              Cerrar
            </button>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}


// ====================================================================
// MAIN
// ====================================================================

export default function Main1() {
  const [modalState, setModalState] = useState({
    isOpen: false,
    title: '',
    description: '',
  });

  const openModal = (title, description) => {
    setModalState({
      isOpen: true,
      title,
      description,
    });
  };

  const closeModal = () => {
    setModalState({
      isOpen: false,
      title: '',
      description: '',
    });
  };

  const navItems = [
    {
      name: 'Docs',
      action: () =>
        openModal(
          'SERVEX Ecosystem Documentation',
          'SERVEX is an AI-driven software ecosystem designed to digitize, automate, and scale Servex’s manual and operational work. Its documentation defines the system architecture, automation flows, module interactions, and the way artificial intelligence operates as the central layer for decision-making, orchestration, and continuous process improvement.'
        ),
    },
    {
      name: 'Automation',
      action: () =>
        openModal(
          'Intelligent Operational Automation',
          'Automation in SERVEX goes beyond rigid scripts or static workflows. Each process is analyzed, executed, and optimized by artificial intelligence, transforming repetitive tasks into autonomous, adaptive, and scalable flows. The goal is to reduce operational friction, minimize human error, and free up time for higher-value work.'
        ),
    },
    {
      name: 'Data',
      action: () =>
        openModal(
          'Data as a Decision Engine',
          'SERVEX centralizes operational data generated by every process and converts it into actionable knowledge. The platform structures, analyzes, and correlates information so artificial intelligence can identify patterns, anticipate issues, and continuously improve operational workflows.'
        ),
    },
    {
      name: 'Use Cases',
      action: () =>
        openModal(
          'AI Applied to Real Work',
          'SERVEX use cases are born directly from daily operations. The platform is designed to address real, repetitive, and mission-critical processes by applying artificial intelligence in a practical and measurable way, delivering immediate operational impact, scalability, and continuous adaptation.'
        ),
    },
    {
      name: 'Support',
      action: () =>
        openModal(
          'AI-Guided Support',
          'Support in SERVEX is part of the ecosystem, not an isolated service. Artificial intelligence monitors process behavior, detects deviations, assists users, and proactively proposes optimizations, ensuring operational stability, continuous evolution, and efficient adoption of the platform.'
        ),
    },
    
  ];

  return (
    <main
      className="
        relative w-full min-h-[90%]
        bg-white text-black
        flex items-center justify-center
        px-3 sm:px-6
      "
    >
      <SimpleModal
        isOpen={modalState.isOpen}
        onClose={closeModal}
        title={modalState.title}
        description={modalState.description}
      />

      <section
        className="
          relative
          w-full max-w-[1400px]
          min-h-[80vh] md:h-[80vh]
          mx-auto
          rounded-[24px]
          bg-white
          overflow-hidden
          flex flex-col
        "
      >
        <header
          className="
            flex items-center justify-between
            px-4 sm:px-6 md:px-10
            py-4 md:py-6
          "
        >
          <div className="flex items-center gap-2">
            <img
              src="/logo2.png"
              alt="Servex Logo"
              className="w-5 h-5 md:w-6 md:h-6 object-contain"
            />
            <span className="font-semibold text-sm md:text-base">
              SVX COPILOT
            </span>
          </div>

          <nav className="hidden md:flex items-center gap-8 text-sm text-black/70">
            {navItems.map((item) => (
              <span
                key={item.name}
                onClick={item.action}
                className="cursor-pointer hover:text-black transition font-medium"
              >
                {item.name}
              </span>
            ))}
          </nav>
        </header>

        {/* Hero */}
        <div
          className="
            flex-1
            grid grid-cols-1 md:grid-cols-2
            gap-10
            px-4 sm:px-6 md:px-10
            pb-6 md:pb-10
            items-center
          "
        >
          {/* Left content */}
          <div>
            <span
              className="
              relative
              inline-block
              top-[-20px]
              mb-5
              rounded-full
              border border-black/10
              px-4 py-1
              text-[11px] sm:text-xs
              "
            >
              Internal Platform · CET Servex US
            </span>

            <h1
              className="
                text-3xl sm:text-4xl md:text-5xl
                font-medium
                leading-tight
                tracking-tight
              "
            >
              Automation <br />
              and Data <br />
              Management <span className="opacity-60">*</span>
            </h1>

            <p
              className="
                mt-5 sm:mt-6
                max-w-md
                text-sm
                text-black/60
              "
            >
              This platform centralizes automation tools and data control systems
              designed to optimize operational processes outside of CET Designer,
              enabling CET Servex teams to work more efficiently, in an organized
              and scalable way.
            </p>

            <div
              className="
                mt-7 sm:mt-8
                flex flex-col sm:flex-row
                sm:items-center
                gap-5 sm:gap-6
              "
            >
              {/* EXTERNAL LINK BUTTON */}
              <a
                href="https://servex-us.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="
                  inline-flex
                  items-center
                  justify-center
                  w-full sm:w-auto
                  rounded-full
                  bg-black
                  px-8 py-3
                  text-sm
                  font-medium
                  text-white
                  shadow-lg
                  transition hover:scale-[1.03]
                "
              >
                Go to SERVEX
              </a>

              <div className="flex items-center gap-4 text-xs text-black/60">
                <span>✓ Centralized processes</span>
                <span>✓ Controlled data</span>
              </div>
            </div>
          </div>

          {/* Right visual (HIDDEN < 800px) */}
          <div
            className="
              hidden md:block
              relative
              w-full
              min-h-[420px]
              md:h-full
            "
          >
            {/* WHITE BASE */}
            <div className="absolute inset-0 rounded-3xl bg-white" />

            {/* SOFT CENTRAL DIAGONAL GRADIENT */}
            <div
              className="
                absolute inset-0
                rounded-3xl
                bg-[radial-gradient(ellipse_at_center,_rgba(236,72,153,0.35)_0%,_rgba(216,180,254,0.35)_35%,_rgba(186,230,253,0.35)_55%,_transparent_70%)]
              "
            />

<div className="relative z-10 flex items-center justify-center overflow-visible">
  <Image
    src="/imgMain1.png"
    alt="Platform preview"
    width={2000}
    height={2000}
    className="
      w-[180%]
      h-auto
      object-contain
      drop-shadow-2xl
    "
  />
</div>

          </div>
        </div>
      </section>
    </main>
  );
}