'use client';

import React, { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Bot, Sparkles, Zap, FileText, Shield, Cloud, RefreshCw } from 'lucide-react';

const AgentInfo = () => {
  const [agentData, setAgentData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const fetchAgentInfo = async () => {
      try {
        setLoading(true);
        const { data, error: supabaseError } = await supabase
          .from('ClientsSERVEX')
          .select('informa_agent_raw')
          .maybeSingle();

        if (supabaseError) throw supabaseError;
        setAgentData(data?.informa_agent_raw || null);
      } catch (err) {
        console.error('Fetch log:', err.message);
        setAgentData(null);
      } finally {
        setLoading(false);
        setTimeout(() => setIsVisible(true), 50);
      }
    };

    fetchAgentInfo();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] bg-[#FFF] font-sans">
        <div className="relative mb-6">
          <div className="w-16 h-16 rounded-full border-4 border-[#EDEBE9] border-t-[#464775] animate-spin" />
          <div className="absolute inset-0 flex items-center justify-center">
            <Bot size={18} className="text-[#464775]" />
          </div>
        </div>
        <p className="text-[#464775] font-bold text-[11px] uppercase tracking-[0.25em] animate-pulse">
          Sincronizando con SVX_AI...
        </p>
        <div className="mt-6 flex gap-1.5">
          {[0, 1, 2, 3, 4].map(i => (
            <div
              key={i}
              className="w-1.5 h-1.5 rounded-full bg-[#464775]/30"
              style={{ animation: `pulse 1.4s ease-in-out ${i * 0.2}s infinite` }}
            />
          ))}
        </div>
      </div>
    );
  }

  if (!agentData) {
    return (
      <div className="flex items-center justify-center min-h-[70vh] px-4 font-sans bg-[#FFF]]">
        <div
          className="max-w-md w-full bg-white border border-[#EDEBE9] rounded-xl shadow-[0_8px_32px_rgba(0,0,0,0.05)] p-12 text-center"
          style={{ animation: 'fadeInUp 0.4s ease forwards' }}
        >
          <div className="flex justify-center mb-8">
            <div className="relative">
              <div className="absolute inset-0 rounded-full bg-[#464775]/10 animate-ping opacity-60" />
              <div className="relative bg-[#FAF9F8] w-20 h-20 rounded-full flex items-center justify-center border border-[#EDEBE9] shadow-inner">
                <Bot size={32} className="text-[#464775]/40" />
              </div>
            </div>
          </div>

          <div className="inline-flex items-center gap-1.5 bg-[#FAF9F8] border border-[#EDEBE9] px-3 py-1 rounded-full mb-4">
            <div className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" />
            <span className="text-[9px] font-black uppercase tracking-[0.2em] text-[#616161]">Pending Analysis</span>
          </div>

          <h3 className="text-[#242424] text-xs font-black uppercase tracking-[0.2em] mb-3">
            Audit in Progress
          </h3>
          <p className="text-[#616161] text-[11px] leading-relaxed mb-8 px-4 font-medium">
            No audit information has been generated by the AI models for this record yet.
            Please check back once the analysis process is complete.
          </p>

          <button
            onClick={() => window.location.reload()}
            className="inline-flex items-center gap-2 px-8 py-3 bg-[#464775] text-white text-[11px] font-bold uppercase tracking-[0.15em] rounded-md hover:bg-[#3b3c63] active:scale-95 transition-all shadow-sm group"
          >
            <RefreshCw size={12} className="group-hover:rotate-180 transition-transform duration-500" />
            Actualizar Reporte
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-[#FFF] min-h-screen py-12 px-4 font-sans text-[#242424]">
      <div
        className="max-w-5xl mx-auto bg-white rounded-xl shadow-[0_12px_24px_rgba(0,0,0,0.06)] border border-[#E1E1E1] overflow-hidden"
        style={{ opacity: isVisible ? 1 : 0, transform: isVisible ? 'translateY(0)' : 'translateY(12px)', transition: 'opacity 0.45s ease, transform 0.45s ease' }}
      >

        {/* Header */}
        <div className="bg-[#FFF] p-5 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-white/15 rounded-lg flex items-center justify-center border border-white/25 shadow-inner">
              <Bot size={18} className="text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2 mb-0.5">
                <h1 className="text-white font-bold text-sm leading-none tracking-tight">Console Executive Report</h1>
                <div className="flex items-center gap-1 bg-white/10 px-2 py-0.5 rounded border border-white/15">
                  <Zap size={9} className="text-yellow-400 fill-yellow-400" />
                  <span className="text-[9px] font-bold text-white/80 tracking-wider">v4.10</span>
                </div>
              </div>
              <p className="text-white/55 text-[10px] uppercase tracking-[0.2em] mt-1 font-bold">Auditoría de Ingeniería</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <div className="hidden sm:flex items-center gap-1.5 px-2.5 py-1 bg-white/10 border border-white/15 rounded text-[9px] font-bold text-white/60 uppercase tracking-wider">
              <Sparkles size={9} className="text-white/50" />
              SVX_PROD
            </div>
            <div className="flex items-center gap-2 px-3 py-1.5 bg-green-400/20 border border-green-400/30 rounded-md">
              <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
              <span className="text-green-100 text-[10px] font-black uppercase tracking-widest">Live Data</span>
            </div>
          </div>
        </div>

        {/* Gradient rule */}
        <div className="h-[3px] w-full bg-gradient-to-r from-[#464775] via-purple-400 to-indigo-300" />

        {/* Meta bar */}
        <div className="px-10 py-3 bg-[#FFF] border-b border-[#EDEBE9] flex items-center gap-4">
          <div className="flex items-center gap-1.5">
            <FileText size={11} className="text-[#464775]" />
            <span className="text-[10px] font-bold text-[#616161] uppercase tracking-wider">Full Document View</span>
          </div>
          <div className="h-3 w-px bg-[#EDEBE9]" />
          <span className="text-[10px] text-[#616161] font-medium">
            {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
          </span>
          <div className="ml-auto flex items-center gap-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-[#464775] shadow-[0_0_6px_rgba(70,71,117,0.5)]" />
            <span className="text-[10px] font-bold text-[#464775] uppercase tracking-wider">Servex US</span>
          </div>
        </div>

        {/* Cuerpo del Reporte */}
        <div className="p-10 lg:p-16">
          <div className="prose prose-slate max-w-none
            prose-headings:text-[#464775] prose-headings:font-bold
            prose-h2:text-2xl prose-h2:border-b prose-h2:border-[#F0F0F0] prose-h2:pb-4 prose-h2:mt-10
            prose-h3:text-lg prose-h3:text-[#464775]/90
            prose-p:text-[#424242] prose-p:leading-relaxed prose-p:text-[15px]
            prose-strong:text-[#464775] prose-strong:font-bold
            prose-li:text-[#424242]">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                table: ({node, ...props}) => (
                  <div className="my-8 overflow-hidden rounded-lg border border-[#EDEBE9] shadow-[0_4px_12px_rgba(0,0,0,0.03)]">
                    <table className="min-w-full divide-y divide-[#EDEBE9]" {...props} />
                  </div>
                ),
                thead: ({node, ...props}) => <thead className="bg-[#FAF9F8]" {...props} />,
                th: ({node, ...props}) => (
                  <th className="px-6 py-4 text-left text-[11px] font-bold text-[#616161] uppercase tracking-wider" {...props} />
                ),
                td: ({node, ...props}) => (
                  <td className="px-6 py-4 text-[13px] text-[#242424] border-t border-[#EDEBE9] bg-white" {...props} />
                ),
                blockquote: ({node, ...props}) => (
                  <div className="bg-[#FAF9F8] border-l-4 border-[#464775] p-6 my-8 rounded-r-lg italic text-[#484644] shadow-sm">
                    {props.children}
                  </div>
                )
              }}
            >
              {agentData}
            </ReactMarkdown>
          </div>
        </div>

        {/* Footer */}
        <div className="bg-[#FFF] border-t border-[#EDEBE9] p-6 px-10 flex justify-between items-center text-[10px] text-[#616161] font-bold uppercase tracking-[0.15em]">
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 bg-[#464775] rounded-full shadow-[0_0_8px_rgba(70,71,117,0.4)]" />
            <p>Powered by <span className="text-[#464775]">Servex_AI Core Logic</span></p>
          </div>
          <div className="flex gap-6 items-center opacity-60">
            <div className="hidden sm:flex items-center gap-1.5">
              <Shield size={10} />
              <span>Azure OAuth 2.0</span>
            </div>
            <div className="flex items-center gap-1.5">
              <Cloud size={10} />
              <span>SVX_PROD</span>
            </div>
          </div>
        </div>
      </div>

      <style>{`
        @keyframes fadeInUp {
          from { opacity: 0; transform: translateY(16px); }
          to   { opacity: 1; transform: translateY(0); }
        }
      `}</style>
    </div>
  );
};

export default AgentInfo;