'use client';

import React, { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabaseClient';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const AgentInfo = () => {
  const [agentData, setAgentData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAgentInfo = async () => {
      try {
        setLoading(true);
        // .maybeSingle() maneja elegantemente si no hay filas sin lanzar excepción
        const { data, error: supabaseError } = await supabase
          .from('ClientsSERVEX')
          .select('informa_agent_raw')
          .maybeSingle();

        if (supabaseError) throw supabaseError;
        setAgentData(data?.informa_agent_raw || null);
      } catch (err) {
        console.error('Fetch log:', err.message);
        setAgentData(null);
      } finally {
        setLoading(false);
      }
    };

    fetchAgentInfo();
  }, []);

  // Estado de Carga Estilo Teams
  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh]">
        <div className="relative">
          <div className="animate-spin rounded-full h-12 w-12 border-4 border-[#EDEBE9] border-t-[#464775]"></div>
        </div>
        <span className="mt-4 text-[#616161] font-medium text-sm animate-pulse italic">Sincronizando con SVX_AI...</span>
      </div>
    );
  }
  
  // Vista cuando no hay información (Sin mención de errores técnicos)
  if (!agentData) {
    return (
      <div className="flex items-center justify-center min-h-[70vh] px-4 font-sans bg-[#FFF]">
        <div className="max-w-md w-full bg-white border border-[#EDEBE9] rounded-xl shadow-[0_8px_32px_rgba(0,0,0,0.05)] p-12 text-center">
          <div className="flex justify-center mb-6">
            <div className="relative">
              {/* Animación de pulso sutil */}
              <div className="absolute inset-0 rounded-full bg-[#464775]/10 animate-ping opacity-75"></div>
              <div className="relative bg-[#FAF9F8] w-20 h-20 rounded-full flex items-center justify-center border border-[#EDEBE9]">
                <svg className="w-10 h-10 text-[#464775]/40" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
            </div>
          </div>
          <h3 className="text-[#242424] text-xs font-black uppercase tracking-[0.2em] mb-4 drop-shadow-[0_1px_1px_rgba(255,255,255,0.8)]">
  Audit in Progress
</h3>
<p className="text-[#616161] text-[11px] leading-relaxed mb-8 px-4 font-medium" style={{ textShadow: '0.5px 0.5px 0px #ffffff' }}>
  No audit information has been generated by the AI models for this record yet. 
  Please check back once the analysis process is complete.
</p>
          <button 
            onClick={() => window.location.reload()}
            className="inline-flex items-center px-8 py-3 bg-[#464775] text-white text-[11px] font-bold uppercase tracking-[0.15em] rounded-md hover:bg-[#3b3c63] transition-all shadow-sm"
          >
            Actualizar Reporte
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-[#F5F5F5] min-h-screen py-12 px-4 font-sans text-[#242424]">
      <div className="max-w-5xl mx-auto bg-white rounded-xl shadow-[0_12px_24px_rgba(0,0,0,0.06)] border border-[#E1E1E1] overflow-hidden">
        
        {/* Header Corporativo */}
        <div className="bg-[#464775] p-5 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-white/20 rounded flex items-center justify-center border border-white/30 shadow-inner">
              <span className="text-white font-black text-xs tracking-tighter">SVX</span>
            </div>
            <div>
              <h1 className="text-white font-bold text-sm leading-none tracking-tight">Console Executive Report</h1>
              <p className="text-white/70 text-[10px] uppercase tracking-[0.2em] mt-1.5 font-bold">Auditoría de Ingeniería</p>
            </div>
          </div>
          <div className="flex items-center gap-2 px-3 py-1.5 bg-green-400/20 border border-green-400/30 rounded-md">
            <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div>
            <span className="text-green-100 text-[10px] font-black uppercase tracking-widest">
              Live Data
            </span>
          </div>
        </div>

        {/* Cuerpo del Reporte */}
        <div className="p-10 lg:p-16">
          <div className="prose prose-slate max-w-none 
            prose-headings:text-[#464775] prose-headings:font-bold
            prose-h2:text-2xl prose-h2:border-b prose-h2:border-[#F0F0F0] prose-h2:pb-4 prose-h2:mt-10
            prose-h3:text-lg prose-h3:text-[#464775]/90
            prose-p:text-[#424242] prose-p:leading-relaxed prose-p:text-[15px]
            prose-strong:text-[#464775] prose-strong:font-bold
            prose-li:text-[#424242]">
            
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{
                table: ({node, ...props}) => (
                  <div className="my-8 overflow-hidden rounded-lg border border-[#EDEBE9] shadow-[0_4px_12px_rgba(0,0,0,0.03)]">
                    <table className="min-w-full divide-y divide-[#EDEBE9]" {...props} />
                  </div>
                ),
                thead: ({node, ...props}) => <thead className="bg-[#FAF9F8]" {...props} />,
                th: ({node, ...props}) => (
                  <th className="px-6 py-4 text-left text-[11px] font-bold text-[#616161] uppercase tracking-wider" {...props} />
                ),
                td: ({node, ...props}) => (
                  <td className="px-6 py-4 text-[13px] text-[#242424] border-t border-[#EDEBE9] bg-white" {...props} />
                ),
                blockquote: ({node, ...props}) => (
                  <div className="bg-[#FAF9F8] border-l-4 border-[#464775] p-6 my-8 rounded-r-lg italic text-[#484644] shadow-sm">
                    {props.children}
                  </div>
                )
              }}
            >
              {agentData}
            </ReactMarkdown>
          </div>
        </div>

        {/* Footer de Auditoría */}
        <div className="bg-[#FAF9F8] border-t border-[#EDEBE9] p-6 px-10 flex justify-between items-center text-[10px] text-[#616161] font-bold uppercase tracking-[0.15em]">
          <div className="flex items-center gap-3">
            <span className="w-2 h-2 bg-[#464775] rounded-full shadow-[0_0_8px_rgba(70,71,117,0.4)]"></span>
            <p>Powered by <span className="text-[#464775]">Servex_AI Core Logic</span></p>
          </div>
          <div className="flex gap-6 items-center opacity-60">
            <span className="hidden sm:block">Security: Azure OAuth 2.0</span>
            <span>Cloud Environment: SVX_PROD</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AgentInfo;